function [fitresult, gof] = createFitexp2(d, a)
%CREATEFIT1(D,A)
%  Create a fit.
%
%  Data for 'Fitted Curve' fit:
%      X Input : d
%      Y Output: a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Oct-2017 13:28:41


%% Fit: 'Fitted Curve'.
[xData, yData] = prepareCurveData( d, a );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [406.819274003059 -0.790773877804884 -49.3302971635946 -2.83787732353216];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fitted Curve' );
h = plot( fitresult, xData, yData );
legend( h, 'a vs. d', 'Fitted Curve', 'Location', 'NorthEast' );
% Label axes
xlabel d
ylabel a
grid on


