function [fitresult, gof] = createFit(d, a)
%CREATEFIT(D,A)
%  Create a fit.
%
%  Data for 'Fitted Curve' fit:
%      X Input : d
%      Y Output: a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Oct-2017 12:06:21


%% Fit: 'Fitted Curve'.
[xData, yData] = prepareCurveData( d, a );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Fitted Curve' );
h = plot( fitresult, xData, yData );
legend( h, 'a vs. d', 'Fitted Curve', 'Location', 'NorthEast' );
% Label axes
xlabel d
ylabel a
grid on


